# Experiment Identification
project_name: "ppffn_latent_reasoning"
experiment_name: "gsm8k_base_sft_no_cot"
seed: 1

# Model Parameters
model_id: "gpt2-medium"
load_model_path: "None"
save_path: "results/"

# Dataset Parameters
dataset_name: "gsm8k"
train_path: "data/gsm8k/gsm_train.json"
val_path: "data/gsm8k/gsm_valid.json"
test_path: "data/gsm8k/gsm_test.json"
max_seq_length: 1024
no_cot: true

# Training Hyperparameters
lr: 3e-5
weight_decay: 0.01
batch_size_training: 92
gradient_accumulation_steps: 1
num_epochs: 3
optimizer_name: "adamw"
num_workers: 16

# Latent Loop / Coconut-Specific Parameters
use_latent_loop: false

# PP-FFN Specific Parameters
ppffn_num_paths: null
ppffn_path_intermediate_size: null
ppffn_aggregation_method: null

# Logging/Saving
save_only_improve: true
wandb_project: "ppffn_project_runs"
debug: false
metric_for_best_model: loss
